version: 2
jobs:
  build:
    docker:
      - image: circleci/golang
    steps:
      - checkout
      - setup_remote_docker
      - run: 
          name: buildimage
          command: |
            cd stable/alpine && \
            docker build -t nginx:test .
  hold:
    type: approval
workflows:
  version: 2
  build_and_test:
    jobs:
      - hold
      - build:
          requires:
            - hold
          filters:
            branches:
              ignore:
                - develop
                - /feature*/
              
