version: 2
jobs:
  build:
    docker:
      - image: circleci/golang
    steps:
      - checkout
      - run: 
          name: buildimage
          command: |
            cd stable/alpine && \
            docker build -t nginx:test .
workflows:
  version: 2
  build_and_test:
    jobs:
      - build